import house1 from "../../assets/House1.png";
import house2 from "../../assets/House2.png";
import house3 from "../../assets/House3.png";
import house4 from "../../assets/House4.png";
import house5 from "../../assets/House5.png";
import house6 from "../../assets/House6.png";

export const estates = [
  {
    id: `REALES001`,
    title: `Lorem Ipsum`,
    description: [
      `At vero eos et iusto odio dignissimos ducimus, qui haec putat, ut ipsi auctori huius disciplinae placet: constituam, quid sit numeranda nec me ab illo inventore veritatis et expedita distinctio nam libero tempore, cum memoriter, tum etiam ac ratione.`,
      `Si sine metu degendae praesidia firmissima filium morte multavit si sine causa? quae fuerit causa, mox videro; interea hoc tenebo, si ob rem voluptas assumenda est, quid sit extremum et inter mediocrem animadversionem atque natum sit, a natura incorrupte.`,
      `Omne animal, simul atque in sanguinem suum tam inportuno tamque crudeli; sin, ut earum motus et accusamus et argumentandum et dolore suo sanciret militaris imperii disciplinam exercitumque in liberos atque haec ratio late patet in quo pertineant non possim.`,
    ],
    features: [
      `Air Conditioning`,
      `Swimming Pool`,
      `Garage`,
      `Sea Access`,
      `Pet Friendly`,
      `Jacuzzi`,
      `Parking Facilities`,
      `Home Office`,
      `Fenced-property`,
      `Alarm system`,
      `CCTV Cameras`,
      `Water Tank`,
      `Solar power`,
      `Wifi`,
      `School Nearby`,
    ],
    beds: 4,
    washroom: 2,
    garage: 1,
    livingroom: 2,
    thumbnail: house1,
  },
  {
    id: `REALES001`,
    title: `Lorem Ipsum`,
    description: [
      `At vero eos et iusto odio dignissimos ducimus, qui haec putat, ut ipsi auctori huius disciplinae placet: constituam, quid sit numeranda nec me ab illo inventore veritatis et expedita distinctio nam libero tempore, cum memoriter, tum etiam ac ratione.`,
      `Si sine metu degendae praesidia firmissima filium morte multavit si sine causa? quae fuerit causa, mox videro; interea hoc tenebo, si ob rem voluptas assumenda est, quid sit extremum et inter mediocrem animadversionem atque natum sit, a natura incorrupte.`,
      `Omne animal, simul atque in sanguinem suum tam inportuno tamque crudeli; sin, ut earum motus et accusamus et argumentandum et dolore suo sanciret militaris imperii disciplinam exercitumque in liberos atque haec ratio late patet in quo pertineant non possim.`,
    ],
    features: [
      `Air Conditioning`,
      `Swimming Pool`,
      `Garage`,
      `Sea Access`,
      `Pet Friendly`,
      `Jacuzzi`,
      `Parking Facilities`,
      `Home Office`,
      `Fenced-property`,
      `Alarm system`,
      `CCTV Cameras`,
      `Water Tank`,
      `Solar power`,
      `Wifi`,
      `School Nearby`,
    ],
    beds: 4,
    washroom: 2,
    garage: 1,
    livingroom: 2,
    thumbnail: house2,
  },
  {
    id: `REALES001`,
    title: `Lorem Ipsum`,
    description: [
      `At vero eos et iusto odio dignissimos ducimus, qui haec putat, ut ipsi auctori huius disciplinae placet: constituam, quid sit numeranda nec me ab illo inventore veritatis et expedita distinctio nam libero tempore, cum memoriter, tum etiam ac ratione.`,
      `Si sine metu degendae praesidia firmissima filium morte multavit si sine causa? quae fuerit causa, mox videro; interea hoc tenebo, si ob rem voluptas assumenda est, quid sit extremum et inter mediocrem animadversionem atque natum sit, a natura incorrupte.`,
      `Omne animal, simul atque in sanguinem suum tam inportuno tamque crudeli; sin, ut earum motus et accusamus et argumentandum et dolore suo sanciret militaris imperii disciplinam exercitumque in liberos atque haec ratio late patet in quo pertineant non possim.`,
    ],
    features: [
      `Air Conditioning`,
      `Swimming Pool`,
      `Garage`,
      `Sea Access`,
      `Pet Friendly`,
      `Jacuzzi`,
      `Parking Facilities`,
      `Home Office`,
      `Fenced-property`,
      `Alarm system`,
      `CCTV Cameras`,
      `Water Tank`,
      `Solar power`,
      `Wifi`,
      `School Nearby`,
    ],
    beds: 4,
    washroom: 2,
    garage: 1,
    livingroom: 2,
    thumbnail: house3,
  },
  {
    id: `REALES001`,
    title: `Lorem Ipsum`,
    description: [
      `At vero eos et iusto odio dignissimos ducimus, qui haec putat, ut ipsi auctori huius disciplinae placet: constituam, quid sit numeranda nec me ab illo inventore veritatis et expedita distinctio nam libero tempore, cum memoriter, tum etiam ac ratione.`,
      `Si sine metu degendae praesidia firmissima filium morte multavit si sine causa? quae fuerit causa, mox videro; interea hoc tenebo, si ob rem voluptas assumenda est, quid sit extremum et inter mediocrem animadversionem atque natum sit, a natura incorrupte.`,
      `Omne animal, simul atque in sanguinem suum tam inportuno tamque crudeli; sin, ut earum motus et accusamus et argumentandum et dolore suo sanciret militaris imperii disciplinam exercitumque in liberos atque haec ratio late patet in quo pertineant non possim.`,
    ],
    features: [
      `Air Conditioning`,
      `Swimming Pool`,
      `Garage`,
      `Sea Access`,
      `Pet Friendly`,
      `Jacuzzi`,
      `Parking Facilities`,
      `Home Office`,
      `Fenced-property`,
      `Alarm system`,
      `CCTV Cameras`,
      `Water Tank`,
      `Solar power`,
      `Wifi`,
      `School Nearby`,
    ],
    beds: 4,
    washroom: 2,
    garage: 1,
    livingroom: 2,
    thumbnail: house4,
  },
  {
    id: `REALES001`,
    title: `Lorem Ipsum`,
    description: [
      `At vero eos et iusto odio dignissimos ducimus, qui haec putat, ut ipsi auctori huius disciplinae placet: constituam, quid sit numeranda nec me ab illo inventore veritatis et expedita distinctio nam libero tempore, cum memoriter, tum etiam ac ratione.`,
      `Si sine metu degendae praesidia firmissima filium morte multavit si sine causa? quae fuerit causa, mox videro; interea hoc tenebo, si ob rem voluptas assumenda est, quid sit extremum et inter mediocrem animadversionem atque natum sit, a natura incorrupte.`,
      `Omne animal, simul atque in sanguinem suum tam inportuno tamque crudeli; sin, ut earum motus et accusamus et argumentandum et dolore suo sanciret militaris imperii disciplinam exercitumque in liberos atque haec ratio late patet in quo pertineant non possim.`,
    ],
    features: [
      `Air Conditioning`,
      `Swimming Pool`,
      `Garage`,
      `Sea Access`,
      `Pet Friendly`,
      `Jacuzzi`,
      `Parking Facilities`,
      `Home Office`,
      `Fenced-property`,
      `Alarm system`,
      `CCTV Cameras`,
      `Water Tank`,
      `Solar power`,
      `Wifi`,
      `School Nearby`,
    ],
    beds: 4,
    washroom: 2,
    garage: 1,
    livingroom: 2,
    thumbnail: house5,
  },
  {
    id: `REALES001`,
    title: `Lorem Ipsum`,
    description: [
      `At vero eos et iusto odio dignissimos ducimus, qui haec putat, ut ipsi auctori huius disciplinae placet: constituam, quid sit numeranda nec me ab illo inventore veritatis et expedita distinctio nam libero tempore, cum memoriter, tum etiam ac ratione.`,
      `Si sine metu degendae praesidia firmissima filium morte multavit si sine causa? quae fuerit causa, mox videro; interea hoc tenebo, si ob rem voluptas assumenda est, quid sit extremum et inter mediocrem animadversionem atque natum sit, a natura incorrupte.`,
      `Omne animal, simul atque in sanguinem suum tam inportuno tamque crudeli; sin, ut earum motus et accusamus et argumentandum et dolore suo sanciret militaris imperii disciplinam exercitumque in liberos atque haec ratio late patet in quo pertineant non possim.`,
    ],
    features: [
      `Air Conditioning`,
      `Swimming Pool`,
      `Garage`,
      `Sea Access`,
      `Pet Friendly`,
      `Jacuzzi`,
      `Parking Facilities`,
      `Home Office`,
      `Fenced-property`,
      `Alarm system`,
      `CCTV Cameras`,
      `Water Tank`,
      `Solar power`,
      `Wifi`,
      `School Nearby`,
    ],
    beds: 4,
    washroom: 2,
    garage: 1,
    livingroom: 2,
    thumbnail: house6,
  },
];
